# This file created by conda-build 26.7.1
# ------------------------------------------------

package:
  name: libbrotlienc
  version: 1.2.0
source:
  fn: brotli-1.2.0.tar.gz
  url: https://github.com/google/brotli/archive/v1.2.0.tar.gz
  sha256: 816c96e8e8f193b40151dad7e8ff37b1221d019dbcb9c35cd3fadbfe6477dfec
build:
  run_exports:
    - libbrotlienc >=1.2.0,<1.3.0a0
  number: 4
  string: h2ddc9cb_4
requirements:
  build:
    - bzip2 1.0.8 h4e30115_10
    - c-ares 1.34.8 h74c22ad_2
    - ca-certificates 2026.7.22 hbd8a1cb_0
    - cctools_impl_osx-arm64 1030.6.3 llvm21_1_h2e2604f_6
    - cctools_osx-arm64 1030.6.3 llvm21_1_h8e84c17_6
    - clang-21 21.1.8 default_h4399b93_6
    - clang_impl_osx-arm64 21.1.8 default_hc11f16d_6
    - clang_osx-arm64 21.1.8 h15b5089_34
    - cmake 4.4.3 hf91ab31_0
    - compiler-rt 21.1.8 hce30654_2
    - compiler-rt21 21.1.8 hdb3d66b_2
    - compiler-rt21_osx-arm64 21.1.8 hb8825d9_2
    - compiler-rt_osx-arm64 21.1.8 hce30654_2
    - icu 78.3 py310h579977c_2
    - krb5 1.22.2 h34f8a20_2
    - ld64_osx-arm64 956.6 llvm21_1_h1a10cc4_6
    - libclang-cpp21.1 21.1.8 default_h4399b93_6
    - libcompiler-rt 21.1.8 hdb3d66b_2
    - libcurl 8.22.0 h6651222_0
    - libcxx 23.1.0 h55c6f16_0
    - libedit 3.1.20250104 pl5321h26f1114_1
    - libev 4.33 h1a92334_3
    - libexpat 2.8.1 hf6b4638_1
    - libiconv 1.18 he4c29f2_3
    - libllvm21 21.1.8 h759d1ac_1
    - liblzma 5.8.3 h8088a28_1
    - libnghttp2 1.68.1 h435687b_1
    - libpsl 0.23.1 hdb0c161_1
    - libsigtool 0.1.3 h98dc951_1
    - libssh2 1.11.1 hbf2880b_1
    - libuv 1.52.1 h1a92334_1
    - libxml2 2.15.3 h5654f7c_1
    - libxml2-16 2.15.3 h5ef1a60_1
    - libzlib 1.3.2 h8088a28_3
    - llvm-tools 21.1.8 hdb3d66b_1
    - llvm-tools-21 21.1.8 h79441dc_1
    - macosx_deployment_target_osx-arm64 11.0 h214bdd9_7
    - ncurses 6.6 he64c551_1
    - ninja 1.13.2 h3feff0a_1
    - openssl 3.6.4 h55eecbc_0
    - rhash 1.4.6 h84a0fba_2
    - sdkroot_env_osx-arm64 26.0 ha3f98da_7
    - sigtool-codesign 0.1.3 h98dc951_1
    - tapi 1600.0.11.8 hb561403_3
    - zstd 1.5.7 hf451053_7
  host:
    - libbrotlicommon 1.2.0 h1dcdb26_4
  run:
    - __osx >=11.0
    - libbrotlicommon 1.2.0 h1dcdb26_4
test:
  commands:
    - test -f $PREFIX/lib/libbrotlienc$SHLIB_EXT
    - test ! -f $PREFIX/lib/libbrotlienc-static.a
about:
  home: http://github.com/google/brotli
  dev_url: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: Brotli compression format
extra:
  recipe-maintainers:
    - CJ-Wright
    - h-vetinari
    - wesm
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260903.2.1
  remote_url: https://github.com/conda-forge/brotli-feedstock
  sha: ceface8d883376fc74f6fc7d82125a1183e810d7
