# This file created by conda-build 26.7.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Aug  8 02:04:17 2026
# ------------------------------------------------

package:
  name: nspr
  version: '4.40'
source:
  url: https://ftp.mozilla.org/pub/nspr/releases/v4.40/src/nspr-4.40.tar.gz
  sha256: c0c1884c627f3db7a783f7c7314c695226b2043696791d15519e7e0578c19bdc
build:
  number: '0'
  run_exports:
    - nspr >=4.40,<5.0a0
  string: hdcbdcf5_0
requirements:
  build:
    - autoconf 2.72 pl5321had7229c_1
    - ca-certificates 2026.7.22 hbd8a1cb_0
    - cctools_impl_osx-64 1030.6.3 llvm19_1_h6ae9dcd_5
    - cctools_impl_osx-arm64 1030.6.3 llvm19_1_h317eeb0_5
    - cctools_osx-64 1030.6.3 llvm19_1_h67a6458_5
    - cctools_osx-arm64 1030.6.3 llvm19_1_h0e16ad9_5
    - clang 19.1.7 default_h1323312_5
    - clang-19 19.1.7 default_hc369343_5
    - clang_impl_osx-64 19.1.7 hc73cdc9_28
    - clang_impl_osx-arm64 19.1.7 h4c5f930_34
    - clang_osx-64 19.1.7 h7e5c614_28
    - clang_osx-arm64 19.1.7 h877a2d5_34
    - clangxx 19.1.7 default_h1c12a56_5
    - clangxx_impl_osx-64 19.1.7 hb295874_28
    - clangxx_impl_osx-arm64 19.1.7 ha2d6da0_34
    - clangxx_osx-arm64 19.1.7 h877a2d5_34
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - gnuconfig 2025.07.09 hd8ed1ab_0
    - ld64_osx-64 956.6 llvm19_1_hf4e8e46_5
    - ld64_osx-arm64 956.6 llvm19_1_hd5dc7e1_5
    - libclang-cpp19.1 19.1.7 default_hc369343_5
    - libcxx 22.1.8 h19cb2f5_0
    - libcxx-devel 19.1.7 h7c275be_2
    - libcxx-headers 19.1.7 h707e725_2
    - libiconv 1.18 h57a12c2_2
    - libintl 0.25.1 h3184127_1
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.3 hbb4bfdb_0
    - libsigtool 0.1.3 h8c25ef7_1
    - libxml2 2.15.3 h0712280_0
    - libxml2-16 2.15.3 h0d7f165_0
    - libzlib 1.3.2 hbb4bfdb_3
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - m4 1.4.21 hf3981d6_0
    - macosx_deployment_target_osx-arm64 11.0 h214bdd9_7
    - make 4.4.1 ha1e9b39_3
    - ncurses 6.6 hcc0dc9a_0
    - openssl 3.6.3 hc881268_1
    - perl 5.32.1 7_h10d778d_perl5
    - sdkroot_env_osx-64 26.0 h62b880e_7
    - sdkroot_env_osx-arm64 26.0 ha3f98da_7
    - sed 4.10 hb63749c_0
    - sigtool-codesign 0.1.3 h8c25ef7_1
    - tapi 1600.0.11.8 h44950e2_3
    - zstd 1.5.7 h3eecb57_6
  host:
    - libcxx 22.1.8 h55c6f16_0
  run:
    - __osx >=11.0
    - libcxx >=19
test:
  commands:
    - test -f ${PREFIX}/lib/libnspr4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libplc4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libplds4${SHLIB_EXT}
    - test -d ${PREFIX}/include/nspr
    - test -f ${PREFIX}/bin/nspr-config
about:
  home: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
  license: MPL-2.0
  license_file: nspr/LICENSE
  summary: A platform-neutral API for system level and libc-like functions.
  description: 'NetScape Portable Runtime (NSPR) provides platform independence for

    non-GUI operating system facilities. These facilities include threads,

    thread synchronization, normal file and network I/O, interval timing and

    calendar time, basic memory management (malloc and free) and shared

    library linking.

    '
  doc_url: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
  dev_url: https://developer.mozilla.org/en-US/docs/MDN
extra:
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
    - marcelotrevisani
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260807.4.1
  remote_url: https://github.com/conda-forge/nspr-feedstock
  sha: cd185077f21ae9792918fa955fcb048b89bb3e70
