# This file created by conda-build 26.7.1
# ------------------------------------------------

package:
  name: openssl
  version: 3.6.4
source:
  url: https://github.com/openssl/openssl/releases/download/openssl-3.6.4/openssl-3.6.4.tar.gz
  sha256: 9bffaa1ad1e07b354c21bd3324ec02fa15579f45a7d0494b3e74bc449b7333ef
build:
  run_exports:
    - openssl >=3.6.4,<4.0a0
  number: 0
  string: h55eecbc_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 21.1.8 hd5368c5_34
    - macosx_deployment_target_osx-arm64 11.0 h214bdd9_7
    - make 4.4.1 h84a0fba_3
    - perl 5.32.1 7_h4614cfb_perl5
  run:
    - __osx >=11.0
    - ca-certificates
  host:
    - __osx >=11.0
test:
  requires:
    - pkg-config
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.6.4" openssl
    - if [[ "$(pkg-config --variable=prefix openssl)" == "" ]]; then exit 1; fi
about:
  home: https://www.openssl.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://docs.openssl.org/master/
extra:
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  feedstock-name: openssl
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260825.9.1
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: 8d5465a6a4ce539acb53d275df6b992a64902e29
